### ISSUE TITLE
SpamAssassin version 3.4 doesn't support ok_languages (but still does ok_locales)

### ISSUE THREAD

**Issue by ElectricWeasel** [johndoh/roundcube-sauserprefs#42]
Hi!

According to:
https://spamassassin.apache.org/full/3.4.x/doc/Mail_SpamAssassin_Conf.html
I have to $config['sauserprefs_dont_override'] = array('ok_languages'); and remove "ok_languages" => "all" from defaults array.
Could we find permanent solution, like SA versions select?

Regards
Rafał

**Comment by JohnDoh** [comment]
It does, assuming you have the TextCat plugin enabled so I think this really comes down to individual configuration. There are other optoins to which are shown by default but require specific plugins to be enabled in SA. I'm not sure there is any way around it other than config. Suggestions welcome.

**Comment by johndoh** [comment]
thinking about this more I believe it is a config issue so I'm going to close this ticket. if any one has any better idea please reopen
