### ISSUE TITLE
Delete E-mail Rules

### ISSUE THREAD

**Issue by Roger-Amorim** [johndoh/roundcube-sauserprefs#43]
Hi,

I have a problem with the "delete" function on email rules section.
Someone can point somenthing I may been missing here ?

![image](https://user-images.githubusercontent.com/36713582/36505250-ab42427a-1731-11e8-8d87-96438b9a82d4.png)

Thanks

**Comment by johndoh** [comment]
the git-master version of this plugin will only work with the git-master version of Roundcube. Releases of stable versions of the plugin are available here https://github.com/johndoh/roundcube-sauserprefs/releases or via composer.
