### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by picarda** [johndoh/roundcube-sauserprefs#44]
Hello,
I'm still having the: http error 500 even with the: ?new_link=true.
I'm using AWS RDS for my databases...

Any ideas?

Thank you.

**Comment by johndoh** [comment]
whats in the roundcube error log?

**Comment by picarda** [comment]
#0 /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php(152): rcube_db_mysql->dsn_options(Array)
#1 /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php(137): rcube_db->conn_create(Array)
#2 /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php(230): rcube_db->dsn_connect(Array, 'w')
#3 /usr/local/lib/roundcubemail/plugins/sauserprefs/lib/Roundcube/rcube_sauserprefs_storage_sql.php(245): rcube_db->db_connect('w')
#4 /usr/local/lib/roundcubemail/plugins/sauserprefs/lib/Roundcube/rcube_sauserprefs_storage_sql.php(53): rcube_sauserprefs_storage_sql->_db_connect('r')
#5 /usr/local/lib/roundcubemail/plugins/sauserprefs/sauserprefs.php(546): rcube_sauserprefs_storage_sql->load_prefs('\\$GLOBAL')
#6 /usr/local/lib/roundcubemail/plugins/sauserprefs/sauserprefs.php(527): sauserprefs->_load_prefs('\\$GLOBAL')
#7 /usr/local/lib/roundcub in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db_mysql.php on line 144

**Comment by johndoh** [comment]
that looks like the strack trace but I don't see an actual error message, did you miss the first line?

though from the trace it looks like it got to `_load_global_prefs()` so it must have connected ok. is the database setup properly, the correct tables etc?

there is an sql_debug log may be that will help also.

**Comment by johndoh** [comment]
no feedback
