### ISSUE TITLE
click problem

### ISSUE THREAD

**Issue by ceylani** [johndoh/roundcube-sauserprefs#50]
Hello,
I have a problem with the sauserprefs plugin. I installed a clean RC 1.3 version and activated jqueryui, sauserprefs plugins but I can not click to view its sub screen in the sauserprefs section. There is no a JS console error.

<img width="1081" alt="sauserprefs" src="https://user-images.githubusercontent.com/4426368/42755360-8c0dd6d0-8900-11e8-9713-fbf0d4899ab0.png">

**Comment by johndoh** [comment]
what is in your rc error log? what version of the plugin are your running?

**Comment by ceylani** [comment]
There is no an error. The version is 1.17.1

**Comment by johndoh** [comment]
In roundcube a white screen like that generally indicates an internal error. Does your PHP log its errors somewhere else than the rc error log? Or may be your rc logging is not working properly? There is not much I can do to help until I know what the error is.

**Comment by ceylani** [comment]
No error in both log. I wrote wrong connection string to see whether logging is working. I saw the database connection error in the rc log file. So, I think that's not a php error.

**Comment by johndoh** [comment]
I'm going to close this because I cannot recreate it. If the problem still exists please reopen with more info.
