### ISSUE TITLE
Blank page when clicking on "General Settings" and "Bayes Settings" on "Spam" tab.

### ISSUE THREAD

**Issue by Tacis** [johndoh/roundcube-sauserprefs#52]
sauserprefs 1.17.1, Roundcube 1.3.8

When I click on "General Settings" or "Bayes Settings" section, blank grey frame is displayed on the right side.

Other sections are displayed OK.

**Comment by johndoh** [comment]
Please provide the relevent entries from your roundcube error log

**Comment by Tacis** [comment]
There's nothing relevant. Last error:

`[03-Dec-2018 14:24:41 +0200]: <nr7hgo4s> SMTP Error: Failed to send data. Message size exceeds server limit in /var/www/html/roundcubemail/program/lib/Roundcube/rcube.php on line 1712 (POST /?_task=mail&_unlock=loading1543839888271&_lang=undefined&_framed=1?_task=mail&_action=send)
`
And I installed sauserpfres yesterday (10 Jan 2019).

**Comment by Tacis** [comment]
https://www.screencast.com/t/SZZldKCP

**Comment by Tacis** [comment]
nginx error log:

`2019/01/12 00:06:43 [error] 13729#13729: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 64 bytes) in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 434" while reading response header from upstream, client: REMOVED, server: REMOVED, request: "GET /?_task=settings&_action=plugin.sauserprefs.edit&_section=general&_framed=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "REMOVED", referrer: "https://REMOVED/?_task=settings&_action=plugin.sauserprefs"`

**Comment by Tacis** [comment]
`2019/01/12 00:11:06 [error] 13728#13728: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2 bytes) in /var/www/html/roundcubemail/plugins/sauserprefs/sauserprefs.php on line 895" while reading response header from upstream, client: REMOVED, server: REMOVED, request: "GET /?_task=settings&_action=plugin.sauserprefs.edit&_section=bayes&_framed=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "REMOVED", referrer: "https://REMOVED/?_task=settings&_action=plugin.sauserprefs"`

**Comment by johndoh** [comment]
interesting. i wonder if this could be a config issue. [Line 895](https://github.com/johndoh/roundcube-sauserprefs/blob/release-1.17/sauserprefs.php#L895) what is sauserprefs_score_inc set to in your config? if you add bayes_auto_learn_threshold_spam to `sauserprefs_dont_override` does the error go away?

**Comment by Tacis** [comment]
```
[root@centos ~]# cat /var/www/html/roundcubemail/plugins/sauserprefs/config.inc.php | grep sauserprefs_score_inc
[root@centos ~]#
```

**Comment by johndoh** [comment]
you can remove from `bayes_auto_learn_threshold_spam` to `sauserprefs_dont_override` if you want. I think the problem is `sauserprefs_score_inc`. May be its having problems reading the default (which is one). What happens if you add `$config['sauserprefs_score_inc'] = 1;` to `/var/www/html/roundcubemail/plugins/sauserprefs/config.inc.php`? How good is your PHP may be you could add some code into sauserprefs::_prefs_block() (sauserprefs.php) to see what `$rcmail->config->get('sauserprefs_score_inc', 1)` returns, it should return 1.

**Comment by Tacis** [comment]
```
[root@centos ~]# systemctl restart nginx.service
[root@centos ~]# cat /var/www/html/roundcubemail/plugins/sauserprefs/config.inc.php | grep sauserprefs_dont_override
// eg. $config['sauserprefs_dont_override'] = array('required_score','rewrite_header Subject');
// eg. $config['sauserprefs_dont_override'] = array('{tests}');
$config['sauserprefs_dont_override'] = array('');
[root@centos ~]# cat /var/www/html/roundcubemail/plugins/sauserprefs/config.inc.php | grep sauserprefs_score_inc
$config['sauserprefs_score_inc'] = 1;
[root@centos ~]#
```

Everything works perfectly now, thank you.

Unfortunately my PHP skills are about zero. :) So I better don't touch the code.
