### ISSUE TITLE
Error connecting to database displayed, but database has been updated

### ISSUE THREAD

**Issue by jedvod** [johndoh/roundcube-sauserprefs#60]
When saving general settings in the extension, It states that it failed to connect to the database but A, when you come out of that specific page and go back, the option's there as though it has been cached or saved and B, the database has been updated with their preference.

**Comment by johndoh** [comment]
I cannot recreate this. What version of the plugin? What version of Roundcube? What database engine? Is there anything in the Roundcube error log?

**Comment by johndoh** [comment]
No feedback
