### ISSUE TITLE
[Roundcube 1.4.11] Fix call to get_form_tags() if class rcmail_action said to be missing

### ISSUE THREAD

**Issue by gnanet** [johndoh/roundcube-sauserprefs#61]
I was facing this issue while trying to use the plugin with Plesk Obsidian's Roundcube Webmail.

https://github.com/johndoh/roundcube-sauserprefs/blob/1fc218d908c1b580ad2a73fc467f8f3477b80244/sauserprefs.php#L261
If an error gets logged about non-existent class rcmail_action, then the function call should changed to 
```
list($form_start, $form_end) = get_form_tags(
```

**Comment by johndoh** [comment]
The git-master version of the plugin requires Roundcube 1.5. Download the correct version of your version of Roundcube https://github.com/johndoh/roundcube-sauserprefs/releases
