### ISSUE TITLE
markasjunk with sauserprefs move to junk will blacklist/whitelist null sender <>

### ISSUE THREAD

**Issue by xpunkt** [johndoh/roundcube-sauserprefs#63]
ups, this should not be added to database, since <> most not be blocked or even whitelisted, i cant remember if spamassassin whitelist_from , blacklist_from use return-path or not, if it does then sauserprefs should not list this sender

**Comment by johndoh** [comment]
huh? are you talking about the sa_blacklist driver which is part of the markasjunk plugin? that uses config settings from this plugin but I think nothing else, its independent code.

can you provide a more detailed explanation, may be a sample message? or just submit a PR with your improvements to the driver.

**Comment by johndoh** [comment]
see if https://github.com/roundcube/roundcubemail/pull/8073 helps

**Comment by johndoh** [comment]
no feedback
