### ISSUE TITLE
Issue when saving address lists

### ISSUE THREAD

**Issue by gabrielt** [johndoh/roundcube-sauserprefs#65]
Hello,
I am getting this error after upgrading to Roundcube 1.5.0 + sauserprefs 1.19.1 when trying to save white/black lists:

PHP Warning:  Invalid argument supplied for foreach() in /[redacted]/plugins/sauserprefs/sauserprefs.php on line 388

Upon inspection, the variable $acts is empty for some reason.

**Comment by johndoh** [comment]
fixed
