### ISSUE TITLE
Address Rules not saved in database

### ISSUE THREAD

**Issue by keenmouse** [johndoh/roundcube-sauserprefs#67]
With Roundcube 1.5.2 and sauserprefs 1.19, when I enter an address rule and save, the interface says "Successfully changed junk settings", but the new rule disappears and nothing is actually saved to the database. Similarly, when there is already a rule in the database and I try to delete it, saving is supposedly successful, but the rule reappears and is not deleted from the database.

This happens under both PHP 7.4 and PHP 8.1.

Roundcube 1.4.13 + Sauserprefs 1.18.4 + PHP 7.4 with identical configuration works fine.

If you need any more details, feel free to ask.

**Comment by johndoh** [comment]
this was fixed in v1.19.2
