### ISSUE TITLE
BLACKLIST/WHITE List inverted? 

### ISSUE THREAD

**Issue by oculos** [johndoh/roundcube-sauserprefs#68]
Hi,

I did an experiment now, and added the following:

```
INSERT INTO spam_assassin_userpref (username,preference,value) VALUES ('user@domain.com','score USER_IN_BLACKLIST','110');
```

To my surprise, the value changed on the interface was the one under the label "Accepted address message score", and not "Rejected address message score". Is there a bug? 

I also realized that, even if the array options on `config.inc.php` seem to be correct, I only get positive values from 1 to 10 on the aforementioned options. What could be the problem here? 

Best,
Francis

**Comment by johndoh** [comment]
the text for the labels got mixed up, its now fixed.

**Comment by oculos** [comment]
What about the array values?

**Comment by johndoh** [comment]
that is fixed too
