### ISSUE TITLE
message not going to junk.

### ISSUE THREAD

**Issue by webtech09** [johndoh/roundcube-sauserprefs#70]
Hi, i installed the plugin, create database and i already can access to the ui of the plugin. i try to add in the address list some domain. and i see it was saved in database, but when i try to send using the domain i input, it is still going to inbox.

**Comment by webtech09** [comment]
i didnt touch any in the config, only type the username and password and database;

**Comment by johndoh** [comment]
SA config and message filtering are separate things, in my experience done by separate processes. Message filtering is outside the scope of this plugin.
