### ISSUE TITLE
Undefined array key 'input_error_class'

### ISSUE THREAD

**Issue by specializedtom** [johndoh/roundcube-sauserprefs#71]
Receiving the following error message when I try to change the score threshold in the General tab. 

AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "input_error_class" in /data/www/roundcube/web/plugins/sauserprefs/sauserprefs.php on line 270', referer: https://webmail.thorptechnology.com.au/?_task=settings&_action=plugin.sauserprefs

I'm running PHP 8.1.10 in PHP-FPM on Apache 2.4 with a MariaDB 10.5 backend.

**Comment by johndoh** [comment]
fixed

**Comment by specializedtom** [comment]
It's no longer coming up with the error on the apache log. However there 
still is an existing issue (on first glance) it looks like a database 
error issue. However, I checked the userprefs table and it does actually 
commit the change to table userprefs when pressing the 'save' button.

Not sure if you are aware of it or not.

- Tom

On 19/09/2022 02:58, Philip Weir wrote:

> Closed #71 [1] as completed.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/johndoh/roundcube-sauserprefs/issues/71
[2] 
https://github.com/johndoh/roundcube-sauserprefs/issues/71#event-7409188524
[3]

**Comment by johndoh** [comment]
Please describe the issue you are facing with this plugin.

**Comment by specializedtom** [comment]
It is when I go to save the settings on the General tab. All the other 
tabs seem to work as intended.

I just tried disabling one of the languages in the list, and then tried 
to save it. However that did not save the changes when going back into 
the General tab.

Here are the apache error logs :

AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 
"remove_header all" in 
/data/www/roundcube/web/plugins/sauserprefs/lib/Roundcube/rcube_sauserprefs_storage_sql.php 
on line 132', referer: 
https://webmail.thorptechnology.com.au/?_task=settings&_action=plugin.sauserprefs.edit&_section=headers&_framed=1
AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 
"remove_header all" in 
/data/www/roundcube/web/plugins/sauserprefs/lib/Roundcube/rcube_sauserprefs_storage_sql.php 
on line 125', referer: https://webmail.thorptechnology.com.au/

Let me know if you need any more information.

- Tom

On 19/09/2022 23:04, Philip Weir wrote:

> Please describe the issue you are facing with this plugin.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/johndoh/roundcube-sauserprefs/issues/71#issuecomment-1250992894
[2]

**Comment by johndoh** [comment]
What do you mean "that did not save"? Are you trying to report an issue or only PHP warnings?

I understand you have some PHP warnings in your log. These are warnings not errors so they will not affect the functionality of the plugin. Any code which causes a warning should be updated for sure and I do not have a PHP8.1 environment to test in right now so reports of any warnings are welcome.

**Comment by johndoh** [comment]
no feedback
