### ISSUE TITLE
Save button is disabled

### ISSUE THREAD

**Issue by sagredo-dev** [johndoh/roundcube-sauserprefs#72]
I have several settings input and save buttons disabled and I don't know why (address rules, general settings), so I cannot add a new rule neither click the "save" button. I tried to truncate the userpref table with no luck.

Any hint appreciated

**Comment by johndoh** [comment]
Are there any JS errors in the browser console?

**Comment by sagredo-dev** [comment]
I get 
```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at String.<anonymous> (sauserprefs.js?s=1655536524:196:59)
    at Function.each (jquery.min.js?s=1658607437:36:2976)
    at HTMLDocument.<anonymous> (sauserprefs.js?s=1655536524:192:11)
    at e (jquery.min.js?s=1658607437:36:30005)
    at t (jquery.min.js?s=1658607437:36:30307)
```
﻿on chromium version 104.0.5112.79

I get this error on firefox version 91.12.0esr

```
Uncaught TypeError: sorting_defaults is undefined
    <anonymous> https://mail.sagredo.eu/plugins/sauserprefs/sauserprefs.js?s=1655536524:196
    each jQuery
    <anonymous> https://mail.sagredo.eu/plugins/sauserprefs/sauserprefs.js?s=1655536524:192
    jQuery 2
        e
        t
```

**Comment by johndoh** [comment]
fixed

**Comment by sagredo-dev** [comment]
Now the form disappeared leaving only the save button. I the console I have

`Uncaught SyntaxError: Invalid or unexpected token (at sauserprefs.js?s=1666510822:363:1)`

This is the line
`rcmail.save_pref({name: 'sauserprefs_sort', value: JSON.stringify(rcmail.env.sauserprefs_sort), env: true});`

**Comment by johndoh** [comment]
At position 1? Do you have a typo on line 362 or may be or just some bad char at the start of the line?

**Comment by sagredo-dev** [comment]
You are right, I'm so sorry. Cutting & paste from github introduced a char that wasn't visible in the text editor
