### ISSUE TITLE
blocklist_from and welcomelist_from do not work

### ISSUE THREAD

**Issue by sagredo-dev** [johndoh/roundcube-sauserprefs#73]
I replaced blacklist_from with blocklist_from and whitelist_from with welcomelist_from in my userpref table, because they are deprecated. The rules are displayed correctly, but it seems that the program is not able to delete the existing rules or add new ones:

<ccrn46ri> sauserprefs error: cannot delete "blacklist_from" = "2634314116@qq.com" for user@domain

It appears that it's still looking for the deprecated preference name when trying to delete.

Thanks for any help

**Comment by johndoh** [comment]
I guess you are running version 1.20 of the plugin. Did you set `sauserprefs_sav4` to true in your config?

**Comment by sagredo-dev** [comment]
Yes I'm running v. 1.20. Unfortunately switching sauserprefs_sav4 to true didn't help as I get the same error

**Comment by johndoh** [comment]
I can't recreate this, please could you provide steps?

**Comment by sagredo-dev** [comment]
Update: I'm not sure that this issue has something to do with #72 that is now solved, but now I don't get errors anymore in the logs/errors file. 
I can create new rules but I cannot delete the existing ones. When I delete a rule (blocklist_from) and click the save button I get a "successfull changed junk settings" message, but the rule appears again in the list and no error is shown in the log this time.

**Comment by johndoh** [comment]
I think I've figured it out and there is a bit of code in the wrong place. My test setup uses a host config file but I'm guessing you don't and that is why we were getting different results. Can you give this patch a try please?

```diff
index 9b1b0b8..30db2e4 100644
--- a/sauserprefs.php
+++ b/sauserprefs.php
@@ -86,6 +86,9 @@ class sauserprefs extends rcube_plugin
         $this->load_config();
         $this->_load_host_config();
 
+        // set SpamAssassin v4 mode (added v1.20)
+        self::$SAv4 = $this->rcube->config->get('sauserprefs_sav4', false);
+
         // Host exceptions
         $hosts = $this->rcube->config->get('sauserprefs_allowed_hosts');
         if (!empty($hosts) && !in_array($_SESSION['storage_host'], (array) $hosts)) {
@@ -1461,8 +1464,5 @@ class sauserprefs extends rcube_plugin
 
         $file = $configs[$_SESSION['storage_host']];
         $this->load_config($file);
-
-        // set SpamAssassin v4 mode (added v1.20)
-        self::$SAv4 = $this->rcube->config->get('sauserprefs_sav4', false);
     }
 }
```

**Comment by sagredo-dev** [comment]
Same as before...

**Comment by johndoh** [comment]
I think it must be something in `sauserprefs->_save()` but I really expected that patch to solve the issue. Can you add some debug code into that function and see if you can work out whats going on?

**Comment by sagredo-dev** [comment]
> I think it must be something in `sauserprefs->_save()` but I really expected that patch to solve the issue. Can you add some debug code into that function and see if you can work out whats going on?

of course yes :-)

**Comment by sagredo-dev** [comment]
It's working as expected now. I've reisstalled and patched and it works. Thank you.
