### ISSUE TITLE
postfixadmin virtual-alias to postfixadmin virtual-mailbox mapping in spamassassin userprefs support

### ISSUE THREAD

**Issue by xpunkt** [johndoh/roundcube-sauserprefs#75]
without this supported only mailbox prefs is supported, when mail is sent to virtual alias there is no way to set prefs for this

i dont know if its better to make a bug report to spamassassin to solve this so spamd / spamc solves it by mapping postfixadmin virtual-alias to postfixadmin virtual-mailbox, if this is core in spamassassin then it would not be any need to solve it here in roundcube :)

what i like to see is already implemented in amavisd-new sa-user and sa-prefs sql mapping, so if roundcube could to the same i be happy to see this supported here

syntectical: virtual-alias => spamassassin-userprefs-user => settings-for-mailbox-user

can this missing map be made ?

**Comment by johndoh** [comment]
In your setup do you use the standard SA prefs table structure with `username`, `preference` and `value` fields? If so then I guess the value you want in the `username` field is not one that the plugin already supports:
```
%u is replaced with the username (from the session info)
%l is replaced with the local part of the username (if the username is an email address)
%d is replaced with the domain part of the username (if the username is an email address or default mail domain if not)
%i is replaced with the email address from the user's default identity
```
so the question is where would the plugin get the value from? May be something like the `config_get` plugin hook would be useful as you could then modify the value of `sauserprefs_userid` dynamically.

**Comment by xpunkt** [comment]
i have set it to use %i, hope this would work, but still not sure it can, lets say this one is remote domain, not a local domain :/

so yes i belive to be secure it most be from postfixadmin database, so it maps from all mailbox that have an alias pointing to mailbox is the only ones that is valid, in that case if sql is checked so, i would use %u so its hardned against sasl login

is there maybe other ways ?

**Comment by xpunkt** [comment]
roundcube does not know any postfixadmin aliases, so there we have the problem, but make the sauserprefs query postfixadmin sql tables should work

**Comment by xpunkt** [comment]
it needs dbi interfaces aswell to load the external map, same as it would for sauserprefs sql, it saves settings in spamassassin userprefs sql, here its just loading postfixadmin virtual-alias table where recipient is ame as %u, result can be multiply or just single, ideally roundcube could verify %i in postfixadmin exists, so it not just a stolen remote mail adresse
