### ISSUE TITLE
user preferences are not being saved on the database

### ISSUE THREAD

**Issue by oculos** [johndoh/roundcube-sauserprefs#76]
I noticed that something weird is happening:

Selecting "use razor2" or "use pyzor" removes the preferences  from the database. Deselecting one of them puts it back, but with "0" as value.

Is there a reason for this or is it a bug?

**Comment by johndoh** [comment]
Only settings which differ from those in `sauserprefs_default_prefs` are saved.

The idea is that the settings in `sauserprefs_default_prefs` match your SpamAssassin config and only settings which the user has changed are saved.
